- test/EventStore.Client.Streams.Tests/sending_and_receiving_large_messages.cs
This test will not pass until EventStore/EventStore#2434 is merged.
> Add Integration Test for Unreasonably Large gRPC Messages

- .github/workflows/ci.yml
- src/Directory.Build.props
- src/EventStore.Client.Common/Constants.cs
- src/EventStore.Client.Common/RequestMetadata.cs
- src/EventStore.Client.UserManagement/EventStoreUserManagerClientExtensions.cs
- src/EventStore.Client/UserCredentials.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/EventStoreClientFixture.cs
- test/EventStore.Client.ProjectionManagement.Tests/EventStoreClientFixture.cs
- test/EventStore.Client.Tests.Common/EventStoreClientFixtureBase.cs
Added: support for bearer tokens
> Support Bearer Tokens in User Credentials

- src/EventStore.Client.Common/protos/gossip.proto
- src/EventStore.Client/ClusterMessage.cs
- src/EventStore.Client/EndPointExtensions.cs
- src/EventStore.Client/EventStore.Client.csproj
- src/EventStore.Client/GossipBasedEndpointDiscoverer.cs
- test/EventStore.Client.Tests/EventStore.Client.Tests.csproj
- test/EventStore.Client.Tests/GossipBasedEndpointDiscovererTests.cs
Fixes https://github.com/eventstore/eventstore/issues/2298
The accompanying server-side PR can be found here: https://github.com/EventStore/EventStore/pull/2519
> Do gossip requests over gRPC

- src/EventStore.Client/ClusterMessage.cs
- src/EventStore.Client/GossipBasedEndpointDiscoverer.cs
- test/EventStore.Client.Tests/GossipBasedEndpointDiscovererTests.cs
The EndPoint could either be an IP or a HostName.
> Rename HttpEndPointIp to HttpEndPointAddress

- src/EventStore.Client/EventStoreClientBase.cs
- src/EventStore.Client/EventStoreClientSettings.cs
Added: Optional ChannelCredentials property on EventStoreClientSettings
> Add ChannelCredentials to EventStoreClientSettings

- .github/workflows/ci.yml
- .gitignore
- gencert.sh
- src/EventStore.Client.Common/protos/persistentsubscriptions.proto
- src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Create.cs
- src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Update.cs
- src/EventStore.Client/EventStoreClientBase.cs
- test/EventStore.Client.Tests.Common/EventStoreClientFixtureBase.cs
Recents changes around `--dev` means we must generate certificates to stand up the eventstore properly.
> Fix Integration Tests

- .github/workflows/regression.Dockerfile
- .github/workflows/regression.yml
Added: nightly CI that tests backwards compatibility
> Proto Regression Tests

- src/EventStore.Client/Uuid.cs
I think that we should do the byte reordering upon transmission/serialization/deserialization to make a cleaner API for the consumer, but that's admittedly low-value.
> Update Uuid.cs docs

- src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Read.cs
Changed: Increase Dealine to Infinity on Persistent Subscriptions / Read
Fixes #81
> Increase gRPC Deadline to Infinite on Persistent Subscriptions

- .github/workflows/ci.yml
- .github/workflows/regression.yml
- src/EventStore.Client/ClusterAwareHttpHandler.cs
- src/EventStore.Client/EventStoreClientSettings.ConnectionString.cs
- test/EventStore.Client.Tests.Common/EventStoreClientFixtureBase.cs
- test/EventStore.Client.Tests/ConnectionStringTests.cs
- refactor
- use theories in tests
- add support for esdb+discover
> Add Support for Single DNS Gossip Seed

- src/EventStore.Client.Streams/StreamSubscription.cs
- test/EventStore.Client.Streams.Tests/Bugs/Issue_104.cs
> Check Disposal Before Invoking CheckpointReached

- src/EventStore.Client.Streams/EventStoreClient.Subscriptions.cs
> Fix Document Errata

- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/deleting_existing_with_subscriber.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/update_existing_with_subscribers.cs
Just to get us unblocked. Filed a ticket to investigate further: https://github.com/EventStore/EventStore-Client-Dotnet/issues/133
> Work around flaky tests

- test/EventStore.Client.PersistentSubscriptions.Tests/FilterTestCase.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/ReadOnlyMemoryExtensions.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/create_filtered.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/deleting_filtered.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/happy_case_filtered.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/happy_case_filtered_with_start_from_set.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/update_existing_filtered.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/update_existing_with_check_point.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/update_existing_with_check_point_filtered.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/update_existing_with_subscribers.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/when_writing_and_filtering_out_events.cs
- test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToStream/update_existing_with_check_point.cs
Added: Extra tests for persistent subscriptions
> Add extra persistent subscriptions tests

- generators/EventStore.Tests.SourceGenerators/MsBuildContextSourceGenerator.cs
Handle the backslashes with verbatim string
> Fix test code generation on windows

- test/EventStore.Client.Tests/SharingProviderTests.cs
For the last assert, had to wait for the factory to be invoked
> Fix flaky SharingProvider test

- test/Directory.Build.props
Fixed: Fluentus.Docker transitive dependency on Newtonsoft.Json
> Fix Transitive Newtonsoft.Json Dependency

- src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Create.cs
- src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Update.cs
Changed: minor changes to exception handling
> Minor Changes to Persistent Subscriptions

- src/EventStore.Client/EventStoreClientBase.cs
- src/EventStore.Client/SharingProvider.cs
- test/EventStore.Client.Tests/SharingProviderTests.cs
Fixed: Client continues to attempt connecting to the server after being disposed.
Closes #257
> Stop connection loop on dispose (DEV-94)

- src/EventStore.Client/EventStore.Client.csproj
Changed: Update bouncy castle to 2.3.1
> Update bouncy castle to 2.3.1
