src/EventStore.Client.Common/protos/operations.proto
src/EventStore.Client.Common/protos/projectionmanagement.proto
src/EventStore.Client.Operations/EventStoreOperationsClient.Admin.cs
src/EventStore.Client.ProjectionManagement/EventStoreProjectionManagementClient.Control.cs
test/EventStore.Client.Operations.Tests/admin.cs
test/EventStore.Client.ProjectionManagement.Tests/restart_subsystem.cs
test/EventStore.Client.Streams.Tests/sending_and_receiving_large_messages.cs

Added: Operations proto contract and implementation
Fixes: https://github.com/EventStore/EventStore/issues/2151
Requires https://github.com/EventStore/EventStore/pull/2446 to be merged.
Add the following to client.Operations:
- MergeIndexes
- Shutdown
- ResignNode
- SetNodePriority
Add RestartSubsystem to client.ProjectionManagement

Add operations proto contract and implementation

---

src/EventStore.Client.Common/protos/streams.proto
src/EventStore.Client.Streams/EventStoreClient.Read.cs
src/EventStore.Client.Streams/ReadState.cs
test/EventStore.Client.Streams.Tests/read_stream_backward.cs
test/EventStore.Client.Streams.Tests/read_stream_forward.cs

When performing a read for a stream, the consumer can decide whether they want the enumeration to throw or to check the read result before continuing.
The ReadState in the example below would currently either be `Ok` or `StreamNotFound`.
i.e.
```
var result = client.ReadStreamAsync(Direction.Forwards, "foo", StreamPosition.Start, 1);
var state = await result.ReadState;
```

Provide a read status which will allow the client to avoid exceptions

---

src/EventStore.Client/ClusterAwareHttpHandler.cs
src/EventStore.Client/ClusterMessage.cs
src/EventStore.Client/EndPointExtensions.cs
src/EventStore.Client/GossipBasedEndpointDiscoverer.cs
src/EventStore.Client/IEndpointDiscoverer.cs
src/EventStore.Client/NotLeaderException.cs
test/EventStore.Client.Tests/ClusterAwareHttpHandlerTests.cs
test/EventStore.Client.Tests/GossipBasedEndpointDiscovererTests.cs

Changed: Update cluster discovery to match the new cluster member info from Event Store server
Fixes https://github.com/EventStore/EventStore/issues/2330
Relies on https://github.com/EventStore/EventStore/pull/2479
- Use httpEndPoint from the cluster member info for cluster discovery
- Change IPEndPoint used in cluster discovery to EndPoint for compatibily with the dns endpoint change (https://github.com/EventStore/EventStore/issues/2478)

Update cluster discovery to remove internal http

---

.github/workflows/ci.yml

Fixed: nuget package push via `dotnet gpr`

Restore Dotnet Tooling Before Running Tool

---

src/EventStore.Client.Streams/DeadLine.cs

Partially Fixes: #29
This PR allows infinite operation timeouts by specifying TimeSpan.MaxValue or Timeout.InfiniteTimeSpan in EventStoreClientOperationOptions.TimeoutAfter.
The second part of the issue (default timeout) has not been dealt with yet. The issue is that just changing the default timeout from 5 seconds to infinity would affect the default timeouts of all operations, not only stream read operations: https://github.com/EventStore/EventStore-Client-Dotnet/blob/master/src/EventStore.Client/EventStoreClientOperationOptions.cs#L10
We could override them in these specific stream read operations but i'm not sure if there's a better approach.

Support infinite timeouts

---

.github/workflows/ci.yml

Fixes https://github.com/EventStore/TrainStation/issues/43
Removed the `oss-v` and left it at `v`. This `v` is used to identify whether a pushed tag is actually a release.
If a tag is pushed, we pull out the branch name from the GITHUB_REF into `version` and `tag`.
- We use the `version` as the package version
- We use the `tag` to kick off the automatic publishing to nuget.

Add Release to Nuget.org

---

src/EventStore.Client.Common/protos/persistentsubscriptions.proto
src/EventStore.Client.Common/protos/shared.proto
src/EventStore.Client.Common/protos/streams.proto
src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Create.cs
src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Delete.cs
src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Read.cs
src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Update.cs
src/EventStore.Client.PersistentSubscriptions/PersistentSubscription.cs
src/EventStore.Client.Streams/EventStoreClient.Append.cs
src/EventStore.Client.Streams/EventStoreClient.Delete.cs
src/EventStore.Client.Streams/EventStoreClient.Metadata.cs
src/EventStore.Client.Streams/EventStoreClient.Read.cs
src/EventStore.Client.Streams/EventStoreClient.Subscriptions.cs
src/EventStore.Client.Streams/EventStoreClient.Tombstone.cs
src/EventStore.Client.Streams/Streams/ReadReq.cs
src/EventStore.Client/StreamIdentifier.cs
test/EventStore.Client.Tests.Common/EventStoreClientFixtureBase.cs

Changed: Restructured stream name for future planned changes

Restructured stream name for future planned changes

---

src/Directory.Build.props

We require minver to use the tag prefix to correctly identify the version we want it to use.

Set Minver to use tag prefix

---

src/EventStore.Client.Operations/EventStoreOperationsClientServiceCollectionExtensions.cs
src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClientCollectionExtensions.cs
src/EventStore.Client.ProjectionManagement/EventStoreProjectionManagementClientCollectionExtensions.cs
src/EventStore.Client.UserManagement/EventStoreUserManagementClientCollectionExtensions.cs

Added: AddXXX extension methods on ServiceCollection for each client

Add Service Collection Extensions to all Clients

---

src/EventStore.Client/ClusterAwareHttpHandler.cs
src/EventStore.Client/EventStoreClientBase.cs
src/EventStore.Client/EventStoreClientConnectivitySettings.cs
src/EventStore.Client/GossipBasedEndpointDiscoverer.cs
test/EventStore.Client.Tests/ClusterAwareHttpHandlerTests.cs
test/EventStore.Client.Tests/GossipBasedEndpointDiscovererTests.cs

Fixes #50
This PR allows the dotnet gRPC client to connect to a cluster running with --insecure (related PR: https://github.com/EventStore/EventStore/pull/2556)

Add GossipOverHttps option to EventStoreClientConnectivitySettings

---

src/EventStore.Client.Common/MetadataExtensions.cs
src/EventStore.Client.Streams/ConditionalWriteResult.cs
src/EventStore.Client.Streams/EventStoreClient.Append.cs
src/EventStore.Client.Streams/EventStoreClient.cs
src/EventStore.Client.Streams/EventStoreClientExtensions.cs
src/EventStore.Client.Streams/IWriteResult.cs
src/EventStore.Client.Streams/SuccessResult.cs
src/EventStore.Client.Streams/WrongExpectedVersionResult.cs
src/EventStore.Client/Exceptions/WrongExpectedVersionException.cs
src/EventStore.Client/StreamPosition.cs
src/EventStore.Client/StreamRevision.cs
test/EventStore.Client.Streams.Tests/append_to_stream.cs
test/EventStore.Client.Streams.Tests/append_to_stream_expected_version_no_stream.cs
test/EventStore.Client.Streams.Tests/deleting_stream.cs
test/EventStore.Client.Streams.Tests/soft_deleted_stream.cs
test/EventStore.Client.Tests/StreamPositionTests.cs
test/EventStore.Client.Tests/StreamRevisionTests.cs

Changed: Convert from StreamPosition to StreamRevision; StreamRevision on IWriteResult

StreamRevision Updates

---

Directory.Build.props
src/Directory.Build.props
src/EventStore.Client/DefaultRequestVersionHandler.cs
src/EventStore.Client/EventStoreClientBase.cs
src/EventStore.Client/EventStoreClientSettings.ConnectionString.cs
src/EventStore.Client/GossipBasedEndpointDiscoverer.cs
test/Directory.Build.props
test/EventStore.Client.Tests.Common/EventStoreClientFixtureBase.cs

Changed: Additionally target netstandard2.1
This PR is similar to the one opened by @dealproc here: https://github.com/EventStore/EventStore-Client-Dotnet/pull/19.
- However it multi-targets both netstandard2.1 and netcoreapp3.1.
- Tests also multi-target both netcoreapp3.0 and netcoreapp3.1 so that they run with both the netstandard2.1 and netcoreapp3.1 version of the client.
I've also added @dealproc as co-author on this commit:  0c4e976
This commit: d806bae6ee58a6db379036f84dd2618cba14e31a fixes the `EventStore.Client.listing_users` flaky test (admin user wasn't yet created)
Co-Authored-By: Richard Bennett <inbox@richardbennett.dev>

Additionally target netstandard2.1

---

src/EventStore.Client.Common/protos/operations.proto
src/EventStore.Client.Operations/EventStoreOperationsClient.Admin.cs
test/EventStore.Client.Operations.Tests/admin.cs
test/EventStore.Client.Operations.Tests/admin_resign_node.cs
test/EventStore.Client.Operations.Tests/admin_shutdown_node.cs

I moved the disruptive client operations (shutdown, resign) into separate test fixtures as they were causing the other tests alongside them to fail.

Add restarting persistent subscriptions

---

src/EventStore.Client.ProjectionManagement/EventStoreProjectionManagementClient.Control.cs
test/EventStore.Client.ProjectionManagement.Tests/reset.cs

This adds a remote call `ResetAsync` to `EventStoreProjectionManagementClient`. Without it the client is not able to reset a projection.
The RPC call was already specified in the protobuf definition.
I am not sure if it is correct to always write a checkpoint.

Add projection reset to client

---

src/EventStore.Client.Operations/EventStoreOperationsClientServiceCollectionExtensions.cs
src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClientCollectionExtensions.cs
src/EventStore.Client.ProjectionManagement/EventStoreProjectionManagementClientCollectionExtensions.cs
src/EventStore.Client.Streams/EventStoreClientServiceCollectionExtensions.cs
src/EventStore.Client.UserManagement/EventStoreUserManagementClientCollectionExtensions.cs

Added: Connection String Support in ServiceCollection extension methods

Add Connection String Overloads for DI Extensions

---

src/EventStore.Client/StreamPosition.cs
src/EventStore.Client/StreamRevision.cs

This is required to satisfy the F# `comparison` constraint, and use comparison operators. Without this, `pos1 < pos2` doesn't compile in F#.

Implement parameterless IComparable for StreamPosition and StreamRevision

---

test/EventStore.Client.PersistentSubscriptions.Tests/update_non_existient.cs

This is a breaking change introduced by https://github.com/EventStore/EventStore/pull/2933
It needs to be merged to master only if https://github.com/EventStore/EventStore/pull/2933 has been merged so that regression tests pass on this repository.

Fix EventStore.Client.update_non_existent.the_completion_fails_with_not_found test

---

src/EventStore.Client.ProjectionManagement/EventStoreProjectionManagementClient.Control.cs

This is the client side of PR https://github.com/EventStore/EventStore/pull/2944
Disabling a projection causes a checkpoint to be written before it is stopped.
Aborting a projection stops the projection without writing a checkpoint.

Send correct writeCheckpoint option when disabling/aborting a projection

---

.github/workflows/ci.yml
test/Directory.Build.props

Currently to see which tests failed in CI, you either need to search the build log or open the test results artifacts. This PR improves that situation by reporting test failures as annotations.

Improve Test Output for CI

---

src/Directory.Build.props
test/EventStore.Client.Operations.Tests/EventStore.Client.Operations.Tests.csproj
test/EventStore.Client.Operations.Tests/EventStoreClientFixture.cs
test/EventStore.Client.PersistentSubscriptions.Tests/EventStoreClientFixture.cs
test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToStream/create_on_existing_stream.cs
test/EventStore.Client.ProjectionManagement.Tests/EventStoreClientFixture.cs
test/EventStore.Client.Streams.Tests/EventStoreClientFixture.cs
test/EventStore.Client.Streams.Tests/Security/SecurityFixture.cs
test/EventStore.Client.Tests.Common/EventStoreClientExtensions.cs
test/EventStore.Client.Tests.Common/EventStoreClientFixtureBase.cs
test/EventStore.Client.Tests.Common/EventStoreTestServer.cs
test/EventStore.Client.Tests.Common/EventStoreTestServerCluster.cs
test/EventStore.Client.Tests.Common/EventStoreTestServerExternal.cs
test/EventStore.Client.Tests.Common/GlobalEnvironment.cs
test/EventStore.Client.Tests.Common/docker-compose.yml
test/EventStore.Client.UserManagement.Tests/EventStore.Client.UserManagement.Tests.csproj
test/EventStore.Client.UserManagement.Tests/EventStoreClientFixture.cs

- Environment variable to prevent spinning up a test server at all (for when you're running one already)
- Wait for $users stream before running tests
- Warm up the streams client to make sure it is connected to leader for both reads and writes
(so that the tests themselves dont have to retry)
- Upgrade grpc

Improve cluster tests in preparation for batch appends

---

src/EventStore.Client.Streams/StreamSubscription.cs

I noticed that when a `Subscription` is disposed, the cancellation token isn't cancelled, but only disposed. This causes any calls to the `.Token` property on it to throw `ObjectDisposedException`
Furthermore, when a subscription is disposed, the actual async reader connection to EventStore is still connected and waiting for the next message. Once one comes in, the code will end up throwing an exception (as it's trying to read the token), and logging that as an error, This can happen much later after the connection is disposed, if your server is not busy.
To patch this, I'm also checking if the token was cancelled After a new message is received. Without this call, this new event/checkpoint would raise an event from a disposed subscription, which is not something that should happen …

Properly cancel the subscription when disposing a subscription

---

src/EventStore.Client.PersistentSubscriptions/PersistentSubscriptionSettings.cs
test/EventStore.Client.PersistentSubscriptions.Tests/Bugs/Issue_1125.cs

I noticed that the defaults don't match the TCP client's while updating persistent subscription docs.
Change the defaults for the following settings when creating a Persistent Subscription:
- maxRetryCount: 10
- readBatchSize: 20
- historyBufferSize: 500
The Issue 1125 test fails with these new defaults. I've created an issue to investigate this here: https://github.com/EventStore/EventStore-Client-Dotnet/issues/139

Update default persistent subscription settings to match TCP client

---

test/Directory.Build.props
test/EventStore.Client.Streams.Tests/deleting_stream.cs

- update test sdk
- add test for streamstate.exists on delete
Intiated by: https://github.com/EventStore/EventStore/issues/3151.

Add Test Case for Delete w/ StreamState.Exists

---

src/EventStore.Client.Operations/EventStoreOperationsClient.cs
src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.cs
src/EventStore.Client.ProjectionManagement/EventStoreProjectionManagementClient.cs
src/EventStore.Client.Streams/EventStoreClient.cs
src/EventStore.Client.UserManagement/EventStoreUserManagementClient.cs
src/EventStore.Client/EventStoreClientBase.cs

- Seal the Client classes (no finalizers here)
- Make dispose/async virtual instead of explicit so it will be called in the standard way
- When disposing EventStoreClient don't create a batchappender if there wasn't one.

Adjustments to Disposal

---

samples/connecting-to-a-cluster/Program.cs
samples/connecting-to-a-single-node/Program.cs
samples/persistent-subscriptions/Program.cs
samples/reading-events/Program.cs
samples/setting-up-dependency-injection/Startup.cs
samples/subscribing-to-streams/Program.cs

To be correctly rendered without redundant lines/spaces, there shouldn't be new lines after `#region` or `#endregion` in the snippets.
Fixed also samples build after change to `AsyncDisposable`.

Removed redundant lines from snippets that were causing formatting issues

---

src/EventStore.Client.Streams/EventStoreClient.Append.cs
src/EventStore.Client.Streams/EventStoreClient.cs

- Recreate batch appender on discovery failure
- Make certain a request cannot be added to a batch appender that is cleaning up
- Make certain IsUsable is called on the same batchappender that we will append with
- Complete the call tidily in the happy path

Adjust batch appender

---

samples/persistent-subscriptions/Program.cs
src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Create.cs
src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Update.cs
src/EventStore.Client.PersistentSubscriptions/PersistentSubscriptionSettings.cs
test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/update_existing_with_check_point.cs
test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/update_existing_with_check_point_filtered.cs
test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/when_writing_and_filtering_out_events.cs
test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToStream/update_existing_with_check_point.cs

Changed: Rename `MaxCheckpointCount` to `CheckPointUpperBound`
Changed: Rename `MinCheckpointCount` to `CheckPointLowerBound`
Changed: Rename `NamedConsumerStrategy` to `ConsumerStrategyName`
Aligns the setting names with the ones in the Persistent Subscriptions RFC.
Fixes https://github.com/EventStore/EventStore-Client-Dotnet/issues/164

Align persistent subscription names with RFC

---

src/EventStore.Client.Streams/EventStoreClient.Delete.cs
test/EventStore.Client.Streams.Tests/append_to_stream.cs
test/EventStore.Client.Streams.Tests/delete_stream_with_timeout.cs
test/EventStore.Client.Streams.Tests/deleting_stream.cs
test/EventStore.Client.Streams.Tests/read_events_linked_to_deleted_stream.cs
test/EventStore.Client.Streams.Tests/soft_deleted_stream.cs

changed: Rename `SoftDeleteAsync` to `DeleteAsync`.
This brings the streams API into compliance with the minimum viable tier.
Fixes https://github.com/eventstore/eventstore-client-dotnet/issues/148

Rename SoftDeleteAsync to DeleteAsync

---

samples/projection-management/Program.cs
src/EventStore.Client/ChannelFactory.cs
src/EventStore.Client/EventStoreClientBase.cs
src/EventStore.Client/Interceptors/ReportLeaderInterceptor.cs
src/EventStore.Client/Interceptors/TypedExceptionInterceptor.cs
src/EventStore.Client/ReconnectionRequired.cs
test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/create_duplicate.cs
test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/create_with_commit_position_larger_than_last_indexed_position.cs
test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToAll/update_existing_with_commit_position_larger_than_last_indexed_position.cs
test/EventStore.Client.PersistentSubscriptions.Tests/SubscriptionToStream/create_duplicate.cs
test/EventStore.Client.Streams.Tests/EventStoreClientFixture.cs
test/EventStore.Client.Streams.Tests/append_to_stream_retry.cs
test/EventStore.Client.Streams.Tests/reconnection.cs
test/EventStore.Client.Streams.Tests/sending_and_receiving_large_messages.cs
test/EventStore.Client.Tests/Interceptors/ReportLeaderInterceptorTests.cs

Added: Set `grpc.max_receive_message_length` to 17MB
Fixed: Force Rediscovery Only when Lost Connection or Unknown error
EventStore allows events of up to 16mb to be written internally. While you can't write events this large through gRPC, you could do so through the TCP client, or through projections. To allow the gRPC clients to read any event that EventStoreDB was able to write, we want to hardcode the max receive message length for all gRPC clients to 17mb.
Some cases where redicovery should have been forced were not handled, are handled now.
Fixes #193

Implement RFC 574

---

.github/workflows/ci.yml

There is an [open issue](https://github.com/NuGet/Home/issues/7503) with `dotnet tool restore`, resulting in
> /usr/share/dotnet/sdk/6.0.200/NuGet.targets(564,5): error : The process cannot access the file '/home/runner/.nuget/NuGet/nugetorgadd.trk' because it is being used by another process. [/tmp/w5mpvqp3.lzr/restore.csproj]
when trying to publish. Applying the workaround in the above mentioned issue.

Workaround For Issue w/ dotnet tool restore

---

src/EventStore.Client.Streams/StreamSubscription.cs

Remove the exception that logs an error when the subscription is cancelled

---

test/EventStore.Client.Streams.Tests/read_stream_backward.cs
test/EventStore.Client.Streams.Tests/read_stream_forward.cs

Added: Tests to verify if $all position is populated when reading stream
Context: https://github.com/EventStore/EventStore/pull/3459

Add tests to verify if $all position is populated when reading stream

---

src/EventStore.Client/EventStoreClientSettings.ConnectionString.cs

Allows channels to open extra connections if they reach the max streams per connection limit (i.e. too may concurrent grpc calls- 100 by default)

Enable multiple http2 connections

---

src/EventStore.Client.Streams/EventStoreClient.cs
src/EventStore.Client/Exceptions/WrongExpectedVersionException.cs

Fixed: Incorrect error message when deleting a stream using gRPC.

Fix incorrect error message when deleting a stream using gRPC

---

test/Directory.Build.props

For https://github.com/advisories/GHSA-5crp-9r3c-p9vr
We have a transitive dependency via Ductus.FluentDocker (tests only)

Bump newtonsoft from 13.0.1 to 13.0.2

---

src/EventStore.Client.Streams/EventStoreClient.Read.cs

Fixed: Dispose the gRPC call underlying a Read if the read is only partially consumed
e.g. when early returning from an await foreach or calling .First().
The IAsyncEnumerable is disposed as before, but now that causes the cancellation of the ResponseStream read, so PumpMessages completes and the call is disposed.
The CancellationTokenSource need not be disposed because it is always cancelled (That is, as long as the user makes any attempt to consume the read - if they don't then the call remains open as before)
Note, I did attempt to remove the channel, but the ReadState task is populated proactively, without the user needing to start consuming the read, so simply having IAsyncEnumerables isn't so straight forward.
Fixes: https://github.com/EventStore/EventStore-Client-Dotnet/issues/219

Dispose the gRPC call underlying a Read if the read is only partially consumed

---

src/EventStore.Client/EventStoreClientBase.cs
src/EventStore.Client/SharingProvider.cs
test/EventStore.Client.Streams.Tests/reconnection.cs
test/EventStore.Client.Tests/SharingProviderTests.cs

e.g. if not authorized, we dont want to run rediscovery again immediately.

Add a delay if producing the ChannelInfo throws an exception

---

.github/workflows/publish.yml

fixed: add source parameter to nuget.org push

Add Required Source Parameter for Nuget.org Push

---

src/EventStore.Client.Streams/EventStoreClient.Read.cs
src/EventStore.Client.Streams/EventStoreClient.cs
test/EventStore.Client.Streams.Tests/Read/ReadAllEventsFixture.cs
test/EventStore.Client.Streams.Tests/Read/read_all_events_backward.cs
test/EventStore.Client.Streams.Tests/Read/read_all_events_forward.cs
test/EventStore.Client.Tests.Common/Fixtures/EventStoreFixture.Helpers.cs

Added: an `EventStore.Client.EventStoreClient.ReadAllAsync(...)` overload accepting `IEventFilter`.
The change is to use EventStore/EventStore#3133
It'd be great to have this feature available.
If something is out of ordinary let me know :)

add filtering to non-subscription reads of $all

---

test/EventStore.Client.Tests.Common/Fixtures/Base/EventStoreTestServer.cs
test/EventStore.Client.Tests.Common/Fixtures/EventStoreFixture.cs
test/EventStore.Client.Tests.Common/GlobalEnvironment.cs

esdb 24.x prints a semver when running with `--version`
System.Version cannot parse this.

Read Semantic Versions when Reading Server Version

---

src/EventStore.Client/EventStoreClientConnectivitySettings.cs
src/EventStore.Client/EventStoreClientSettings.ConnectionString.cs
src/EventStore.Client/HttpFallback.cs
src/EventStore.Client/SingleNodeChannelSelector.cs
src/EventStore.Client/SingleNodeHttpHandler.cs
test/EventStore.Client.Tests.Common/Fixtures/Base/EventStoreClientFixtureBase.cs
test/EventStore.Client.Tests.Common/Fixtures/EventStoreTestNode.cs
test/EventStore.Client.Tests/ConnectionStringTests.cs

Changed: Return null for discovery mode or multiple hosts in connection string
Changed: Updated Address field to support null returns
Fixed: #260 
This PR refactors the Address property resolution logic in the `EventStoreClientConnectivitySettings` class. Previously, when a cluster was specified in the connection string, the Address property defaulted to localhost:2113, which was inconsistent behavior. With this change, the logic now returns null when a cluster is specified. New tests have also been added to cover various connection string scenarios.
| Connection string                             | Behaviour before | Behaviour after |
| --------------------------------------------- | ---------------- | --------------- |
| esdb://localhost:1234                         | localhost:1234   | …

DEV-266 - Return null for discovery mode or multiple hosts in connection string

---

src/EventStore.Client/HttpFallback.cs

Changed: Add certificate in HTTP fallback handler
Was missed in #281

DEV-92 - Add certificate in HTTP fallback handler

---

src/EventStore.Client.PersistentSubscriptions/EventStorePersistentSubscriptionsClient.Read.cs
src/EventStore.Client.Streams/EventStoreClient.Subscriptions.cs

Fixed: #290 
Changed: Disable throwing compiler errors for obsolete code

Disable throwing compiler errors for obsolete code

---

.github/workflows/publish.yml
gencert.ps1
gencert.sh
samples/secure-with-tls/docker-compose.certs.yml
test/EventStore.Client.Tests.Common/Fixtures/CertificatesManager.cs
test/EventStore.Client.Tests.Common/docker-compose.certs.yml
test/EventStore.Client.Tests.Common/docker-compose.cluster.yml
test/EventStore.Client.Tests.Common/docker-compose.yml

Changed: Updated everywhere to pull es-gencert-cli from Cloudsmith

DEV-45-2 - Pull es-gencert-cli from Cloudsmith

---

samples/Samples.sln
samples/diagnostics/Program.cs
samples/diagnostics/diagnostics.csproj
samples/user-certificates/Program.cs
samples/user-certificates/user-certificates.csproj

Changed: Add OTel and User certificates samples

Add OTel and User certificates samples

---

src/EventStore.Client.Streams/EventStoreClient.Append.cs
src/EventStore.Client.Streams/EventStoreClient.Read.cs
src/EventStore.Client.Streams/EventStoreClient.cs
src/EventStore.Client/EventTypeFilter.cs
src/EventStore.Client/StreamFilter.cs

Changed: Updated Streams APIs to account for `null`, `StreamTypeFilter.None` & `EventTypeFilter.None` event filter scenarios.

Handle missing null/None event filter cases on Streams APIs

---

src/EventStore.Client/Common/Diagnostics/ActivitySourceExtensions.cs
src/EventStore.Client/Common/Diagnostics/EventMetadataExtensions.cs

Changed: Use TryParseValue when attempting to parse event metadata as JsonDocument, to prevent _unneccessary_ exception with catch.
Changed: Use TryGetProperty when extracting tracing metadata to prevent _unneccessary_ exception being thrown in absence thereof.
Changed: Added short-circuit to tracing logic to prevent unnecessary parsing of event data et al when there are no diagnostic listeners.
Fixes https://github.com/EventStore/EventStore-Client-Dotnet/issues/310

Tracing improvements

---

src/EventStore.Client.Streams/EventStoreClient.Append.cs
src/EventStore.Client/Common/Diagnostics/ActivitySourceExtensions.cs
src/EventStore.Client/Common/Diagnostics/EventMetadataExtensions.cs
src/EventStore.Client/EventStore.Client.csproj
test/EventStore.Client.PersistentSubscriptions.Tests/Diagnostics/PersistentSubscriptionsTracingInstrumentationTests.cs
test/EventStore.Client.Streams.Tests/Diagnostics/StreamsTracingInstrumentationTests.cs
test/EventStore.Client.Tests.Common/Fixtures/EventStoreFixture.Helpers.cs

Changed: Made trace context injection/extraction more robust.
Changed: Trace context injection/extraction will only occur when event content type is json.
Fixes https://github.com/EventStore/EventStore-Client-Dotnet/issues/316

Fix tracing injection when event is non-JSON

---

src/EventStore.Client.Streams/EventStoreClient.Append.cs
src/EventStore.Client/Common/Diagnostics/ActivitySourceExtensions.cs
src/EventStore.Client/Common/Diagnostics/Core/Tracing/TracingMetadata.cs
src/EventStore.Client/Common/Diagnostics/EventMetadataExtensions.cs
test/EventStore.Client.Streams.Tests/Diagnostics/StreamsTracingInstrumentationTests.cs
test/EventStore.Client.Tests.Common/Fixtures/DiagnosticsFixture.cs
test/EventStore.Client.Tests.Common/Fixtures/EventStoreFixture.Helpers.cs

Changed: Removed check for "application/json" when tracing subscriptions
Changed: Try to inject trace context in metadata regardless of event type.
Changed: Extract trace context from Event rather than OriginalEvent to account for link metadata.
Fixed: Fix check for parent context when extract propagation context fails
Previously, `if (parentContext == null) return;` was returning false even though the extraction of the propagation context had failed. I changed it to `parentContext == default(ActivityContext)` because the tracing method returns a default `ActivityContext` when it fails to extract the trace context.

Fix check for parent context when extract propagation context fails

---

.github/workflows/publish.yml
src/EventStore.Client/Common/Diagnostics/ActivitySourceExtensions.cs
src/EventStore.Client/EventStore.Client.csproj
test/EventStore.Client.Streams.Tests/Diagnostics/StreamsTracingInstrumentationTests.cs
test/EventStore.Client.Streams.Tests/Subscriptions/subscribe_to_stream.cs
test/EventStore.Client.Tests.Common/Fixtures/DiagnosticsFixture.cs

Fixed: Account for nullable events when collecting telemetry during tracing in subscription

Account for nullable events

---

src/EventStore.Client.Streams/EventStoreClient.Append.cs
src/EventStore.Client/Common/Diagnostics/ActivitySourceExtensions.cs
src/EventStore.Client/Common/Diagnostics/ActivityTagsCollectionExtensions.cs

Fixed: Account for standard ports when collecting tags
Fixes #322

Account for standard ports when collecting tags

---

src/KurrentDB.Client/Core/KurrentDBClientSettings.ConnectionString.cs
src/KurrentDB.Client/Streams/KurrentDBClient.cs
test/KurrentDB.Client.Tests/ConnectionStringTests.cs

Fixes #343 
The http message handler was unnecessarily called when client settings were created, leading to infinite recursion in HTTP handler creation for the .NET 4.8 framework target

fix: unnecessary http message handler invocation

---

.github/workflows/base.yml
.github/workflows/dispatch-ee.yml

Allow specifying `kurrentdb-image` and `kurrentdb-registry`. If `kurrentdb-image` is provided, the `KURRENTDB_DOCKER_IMAGES` variable is not used.

Allow specifying custom KurrentDB docker images in dispatch tests

---

.github/workflows/base.yml

They are actually the same registry but logging in will allow the image to be pulled from any of them regardless of how it is addressed

Log in to additional registries
